"""Regenerate docs/findings.md from mddbmeta.findings.CATALOG."""

from pathlib import Path

from mddbmeta.findings import CATALOG

GROUPS = [("CONT", "Continuity"), ("SEQ", "Sequences"), ("CMP", "Completeness"), ("CONS", "Consistency"),
          ("REP", "Replicas"), ("MELD", "Replica exchange (MELD)"), ("STEP", "Steps"), ("ROLE", "Roles"), ("ORDER", "Ordering"),
          ("LIN", "Lineage"), ("MINE", "Mining"), ("FMT", "Formats"), ("MRG", "Trajectory merge"),
          ("SCH", "Schema"), ("LOAD", "Loading"), ("ENG", "Engines"), ("REC", "Reconcile")]  # fmt: skip


def main() -> None:
    lines = [
        "# Finding codes",
        "",
        "Every finding carries a stable `code`; match on it in scripts and CI. Messages may change.",
        "Severities: `error` (exit 2 from `validate`/`export`), `warning` (exit 2 with `--strict`), "
        "`suggestion`, `info` (shown with `-v`). Some codes are downgraded in context "
        "(e.g. `CONT005` is `info` between preparation stages).",
        "",
        "<!-- generated by scripts/gen_findings_doc.py; tests/test_docs.py keeps it in sync -->",
        "",
    ]
    for prefix, title in GROUPS:
        codes = sorted(
            (c for c in CATALOG.values() if c.code.rstrip("0123456789") == prefix),
            key=lambda c: c.code,
        )
        lines += [f"## {title}", "", "| Code | Default severity | Meaning |", "|---|---|---|"]
        lines += [f"| `{c.code}` | {c.severity.value} | {c.title} |" for c in codes]
        lines.append("")
    out = Path(__file__).resolve().parents[1] / "docs" / "findings.md"
    out.write_text("\n".join(lines))
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
